### ISSUE TITLE
Discuss project/publication ideas for ICA2020

### ISSUE THREAD

**Issue by fhopp** [medianeuroscience/icore#6] opened 2019-09-26 01:19 UTC
Outline project ideas to be submitted (likely as extended abstracts) to ICA.

**Comment by fhopp** [comment] 2019-09-27 16:32
I believe we currently have three potential project ideas with iCoRe that we could turn into conference submissions:  
1) Large-scale, cross-country sharing study 
2) Regional covariates' (pathogen stress, press freedom, democracy index, ...) impact on news coverage (e.g., sentiment, moral frames, "polarization") ... 
3) Framing of recycling, together with Ron Rice.

**Comment by jacobtfisher** [comment] 2019-10-01 19:53
Duplicate of medianeuroscience/lab-docs/17

**Closed** 2019-10-09 19:30 UTC
Labels: conferences, decisions
